name:                haskell-tictactoe
version:             0.1.0.0
github:              "githubuser/haskell-tictactoe"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A playground for messing about with Haskell

dependencies:
- base-noprelude >= 4.7 && < 5
- classy-prelude
- errors
- fmt
- lens
- mtl
- monad-loops
- split

default-extensions:
# - ApplicativeDo
# - BangPatterns
# - ConstraintKinds
# - DataKinds
# - DefaultSignatures
# - DeriveFoldable
- DeriveFunctor
# - DeriveGeneric
# - DeriveLift
# - DeriveTraversable
# - DerivingStrategies
# - EmptyCase
# - ExistentialQuantification
- FlexibleContexts
# - FlexibleInstances
# - FunctionalDependencies
# - GADTs
- GeneralizedNewtypeDeriving
# - InstanceSigs
# - KindSignatures
# - LambdaCase
# - MultiParamTypeClasses
# - MultiWayIf
# - NamedFieldPuns
- OverloadedStrings
# - PatternSynonyms
# - RankNTypes
# - ScopedTypeVariables
# - StandaloneDeriving
# - TupleSections
# - TypeApplications
# - TypeFamilies
# - TypeFamilyDependencies
# - TypeOperators

library:
  source-dirs: src

executables:
  haskell-tictactoe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    # - -threaded
    - -rtsopts
    # - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - haskell-tictactoe
    - warp

tests:
  haskell-tictactoe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-tictactoe
    - hspec
